# Generated by Django 3.2.16 on 2023-01-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
